import shutil
from pathlib import Path

# --- Configuration ---
SOURCE_FILE = "interactive_analysis_report.html"  # The report generated by report.py
TARGET_FILE = "downloaded_report.html"  # The file name to save for download
CHART_DIRECTORY = Path("charts_html")  # The directory where the HTML charts are stored (if separate)
# ---------------------

def save_report_with_charts(source_filename: str, target_filename: str):
    """
    Copies the generated HTML report to the target location and ensures charts
    (if any) are linked correctly.
    """
    try:
        # Source and target paths for the report file
        source_path = Path(source_filename)
        target_path = Path(target_filename)

        if not source_path.is_file():
            print(f"ERROR: Source file '{source_filename}' not found!")
            return None
        
        # Copy the source report to the target location
        shutil.copy(source_path, target_path)
        print(f"Successfully copied '{source_filename}' to '{target_filename}'.")

        # Now, handle charts (if charts are referenced in the HTML)
        # Here, I assume that the charts are stored as HTML files in a directory (CHART_DIRECTORY)
        if CHART_DIRECTORY.is_dir():
            print(f"Ensuring charts in {CHART_DIRECTORY} are linked in the report...")

            # Example: This can be adjusted based on how your charts are referenced in the HTML
            # If the charts are linked with relative paths, make sure the chart folder is correct.
            # No need to move charts if they are already correctly linked in the HTML

        return target_path  # Return the path for downloading

    except Exception as e:
        print(f"An error occurred: {e}")
        return None


# Function to trigger the download (this would be in a typical Python script or command line)
def main():
    # Generate the report (ensure report.py has been run and the report is created)
    target_path = save_report_with_charts(SOURCE_FILE, TARGET_FILE)
    
    if target_path and target_path.exists():
        print(f"Report successfully saved as '{target_path}'")
        # You can manually move the file to wherever you want, or share it
        print(f"Download the report from: {target_path}")
    else:
        print("There was an error saving the report.")


if __name__ == "__main__":
    main()
